### ISSUE TITLE
appleboy/drone-jenkins:1.3.2-linux-amd64 Dockerfile?

### ISSUE THREAD

**Issue by brianjmurrell** [appleboy/jenkins-action#7]
Can you publish the Dockerfile that builds https://hub.docker.com/r/appleboy/drone-jenkins/?

**Comment by cardonator** [comment]
It's just in the other repo this one pivots from. https://github.com/appleboy/drone-jenkins/tree/master/docker

**Comment by appleboy** [comment]
Please try the master version.
