### ISSUE TITLE
Trigger job within a folder

### ISSUE THREAD

**Issue by chris-metz** [appleboy/jenkins-action#8]
Is it possible to trigger a job that's inside of a jenkins folder?

I tried by using 

```
job: FOLDERNAME/job/JOBNAME
```

but with no success

**Comment by prabirgres** [comment]
I am having the same issue for this one

**Comment by parameshjava** [comment]
I am also facing the same issue.

**Comment by appleboy** [comment]
I will take it

**Comment by appleboy** [comment]
currently support subfolder.
